### PR TITLE
Added ON_PROCESS error

### PR DESCRIPTION
**Pull request by KarimovMurodilla**
If transaction in status processing, returns -31099 code with error message

### CODE REVIEW

**Comment by begyy** [comment]
@KarimovMurodilla pypi da account bering dostup berb qoyaman otgayam deploy qivorish kere agar ilojis bosa paymega documentatsiya ozbechada yozb qoysezam zor bolardi :)

**Comment by KarimovMurodilla** [comment]
> @KarimovMurodilla pypi da account bering
karimovmurodilla15@gmail.com

**Comment by KarimovMurodilla** [comment]
> ilojis bosa paymega documentatsiya ozbechada yozb qoysezam zor bolardi

Aha Hudo hohlasa bir qilib koraman, qoldan kegancha

**Comment by begyy** [comment]
image
@KarimovMurodilla toplmadi account pypi.org dan regdan otvoling

**Comment by KarimovMurodilla** [comment]
username: murodilla

**Comment by begyy** [comment]
@KarimovMurodilla invite yubordm

**Comment by begyy** [comment]
@KarimovMurodilla gmailga link borgan qabul qivorarsiz

**Comment by KarimovMurodilla** [comment]
aha hop

**Comment by KarimovMurodilla** [comment]
image

**Pull request merged**
